export const products = [
    {
        id:1,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:2,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:3,
        name : 'Muzzarela',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:4,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:5,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:6,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:7,
        name : 'Muzzarela',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:8,
        name : 'Muzzarela',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Pizzas',
    },
    {
        id:9,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:10,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:11,
        name : 'Empanadas',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:12,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:13,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:14,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:15,
        name : 'Empanadas',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:16,
        name : 'Empanadas',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Empanadas',
    },
    {
        id:17,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:18,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:19,
        name : 'Sandwiches',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:20,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:21,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:22,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:23,
        name : 'Sandwiches',
        imagen: "../assets/napolitana.png",
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:24,
        name : 'Sandwiches',
        imagen: '../assets/muzza.png',
        price: 1750,
        category: 'Sandwiches',
    },
    {
        id:25,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:26,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:27,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:28,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:29,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:30,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:31,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    },
    {
        id:32,
        name: 'Bebidas',
        price: 1750,
        category: 'Bebidas',
    }
]